import { IFormula } from "@/types/formula";

export const formulas: IFormula[] = [
  { name: "Формула 1", formula: "E = mc^2" },
  { name: "Формула 2", formula: "F = ma" },
  { name: "Формула 3", formula: "V = d/t" },
  { name: "Формула 4", formula: "a = (vf - vi) / t" },
  { name: "Формула 5", formula: "P = F/A" },
  { name: "Формула 6", formula: "T = m * g * h" },
  { name: "Формула 7", formula: "I = V/R" },
  { name: "Формула 8", formula: "Q = m * ΔT * c" },
  { name: "Формула 9", formula: "n = N / V" },
  { name: "Формула 10", formula: "L = m * v * r" },
  { name: "Формула 11", formula: "F = G * (m1 * m2) / r^2" },
  { name: "Формула 12", formula: "P = E/t" },
  { name: "Формула 13", formula: "ρ = m/V" },
  { name: "Формула 14", formula: "Δs = v * t" },
  { name: "Формула 15", formula: "Q = mcΔT" },
  { name: "Формула 16", formula: "P = W/t" },
  { name: "Формула 17", formula: "U = m * g * h" },
  { name: "Формула 18", formula: "I = P/V" },
  { name: "Формула 19", formula: "F = k * x" },
  { name: "Формула 20", formula: "W = F * d" },
  { name: "Формула 21", formula: "Q = mlΔT" },
  { name: "Формула 22", formula: "P = Fv" },
  { name: "Формула 23", formula: "ρ = m/V" },
  { name: "Формула 24", formula: "v = at" },
  { name: "Формула 25", formula: "F = q * E" },
  { name: "Формула 26", formula: "W = Fd cos θ" },
  { name: "Формула 27", formula: "Q = mL" },
  { name: "Формула 28", formula: "P = IV" },
  { name: "Формула 29", formula: "F = μN" },
  { name: "Формула 30", formula: "U = 1/2 * k * x^2" },
];
