import { IFormula } from "@/types/formula";

export const formulas: IFormula[] = [
  { name: "Формула 1", formula: "E = m*c^2" },
  { name: "Формула 2", formula: "F = m*a" },
  { name: "Формула 3", formula: "V = d/t" },
  { name: "Формула 4", formula: "a = (f - i) / t" },
  { name: "Формула 5", formula: "P = F/A" },
  { name: "Формула 6", formula: "T = m * g * h" },
  { name: "Формула 7", formula: "I = V/R" },
  { name: "Формула 8", formula: "Q = m * T * c" },
  { name: "Формула 9", formula: "n = N / V" },
  { name: "Формула 10", formula: "L = m * v * r" },
  { name: "Формула 11", formula: "F = G * (m * y) / r^2" },
  { name: "Формула 12", formula: "P = E/t" },
  { name: "Формула 13", formula: "ρ = m/V" },
  { name: "Формула 14", formula: "Δs = v * t" },
  { name: "Формула 15", formula: "Q = m*c*T" },
  { name: "Формула 16", formula: "P = W/t" },
  { name: "Формула 17", formula: "U = m * g * h" },
  { name: "Формула 18", formula: "I = P/V" },
  { name: "Формула 19", formula: "F = k * x" },
  { name: "Формула 20", formula: "W = F * d" },
  { name: "Формула 21", formula: "Q = m*l*T" },
  { name: "Формула 22", formula: "P = F*v" },
  { name: "Формула 23", formula: "ρ = m/V" },
  { name: "Формула 24", formula: "v = a*t" },
  { name: "Формула 25", formula: "F = q * E" },
  { name: "Формула 26", formula: "W = F*d" },
  { name: "Формула 27", formula: "Q = m*L" },
  { name: "Формула 28", formula: "P = I*V" },
  { name: "Формула 29", formula: "F = u*N" },
  { name: "Формула 30", formula: "U = 1/2 * k * x^2" },
];
